Added terraform-pod utility
mightydevops/shell-utils pull request #5
Opened 2021-12-08 03:14 UTC by MikhailKorol-saritasa

Moved from https://github.com/mightydevops/saritasa-cloud-eks-cluster/pull/17
Tested a while, works fine.
There are a couple of suggestions:
- autoconnect to teleport
- autoswitch to cloud context
What do you think about?

2021-12-09 08:44 UTC, DanilaKazakevich commented
@MikhailKorol-saritasa you can just implement user input "Are you logged in saritasa.cloud k8s cluster? Yes [Y] No [N]". If "No" print command which user should do and exit.

2021-12-09 08:46 UTC, DanilaKazakevich commented on terraform/terraform-pod
> +echo "Awating pod ready:"
Was Typo
```suggestion
echo "Pod is ready:"
```

2021-12-09 08:55 UTC, DanilaKazakevich commented on terraform/terraform-pod
> +{ kubectl logs -f $pod & echo $! > pid;} | { sed '/READY!/ q' && kill -9 $(cat pid) && rm pid;}
I think this solution is good, but for future you can use exec in Readness probe which will try to output file that creates in the last command of k8s pod.

2021-12-09 08:56 UTC, DanilaKazakevich approved these changes

2021-12-10 04:24 UTC, kseniyashaydurova approved these changes

2021-12-10 04:24 UTC, kseniyashaydurova commented on terraform/terraform-pod
> +- git@github.com:mightydevops/saritasa-cloud-eks-cluster/cluster/production/utils/terraform-base?ref=feature/git-crypt-and-user
Please update path to terraform base, I made some small changes there

2021-12-10 04:24 UTC, kseniyashaydurova commented on terraform/terraform-pod
> +kubectl wait --for=condition=Ready --timeout=120s $pod
Please add `terraform` namespace in all `kubectl` commands, so script wouldn't be broken when user is in another ns

2021-12-10 04:24 UTC, kseniyashaydurova commented on terraform/terraform-pod
> +# mb replace by wget?
Is it actual comment?

2021-12-10 04:31 UTC, kseniyashaydurova commented
Now it is so convenient to start new terraform pods! Thank you!

2021-12-10 05:23 UTC, roman-mightydevops approved these changes

2021-12-10 10:24 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +kubectl wait --for=condition=Ready --timeout=120s $pod
Added it globally to context

2021-12-10 10:24 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +# mb replace by wget?
Nope, removed, thnx

2021-12-10 10:25 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +- git@github.com:mightydevops/saritasa-cloud-eks-cluster/cluster/production/utils/terraform-base?ref=feature/git-crypt-and-user
I have some updates for your, wait for it :)

2021-12-14 02:55 UTC, kseniyashaydurova commented on terraform/terraform-pod
> +cat << EOF  >  terraform-pod-patch.yaml
Let's also add deletion of  `terraform-pod-watch.yaml` and `kustomization.yaml`  files from project's folder after terraform pod destruction?

2021-12-14 03:08 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +cat << EOF  >  terraform-pod-patch.yaml
I left it for purpose, for example if you need to tune manifest after usage or clean resources on script failure. But we can add `cleanup` flag as condition for that action.

2021-12-16 11:08 UTC, kseniyashaydurova commented on terraform/terraform-pod
> +cat << EOF  >  terraform-pod-patch.yaml
It is just not convenient to git them from original repo all the time :)

2021-12-22 01:01 UTC, dmitry-mightydevops commented
@MikhailKorol-saritasa @kseniyashaydurova has this been moved to https://github.com/saritasa-nest/saritasa-cloud-eks-cluster?

2021-12-22 01:23 UTC, dmitry-mightydevops commented
s

2021-12-22 01:23 UTC, dmitry-mightydevops requested changes

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +kubectl config use-context teleport.saritasa.cloud-teleport.saritasa.cloud
this context could be different and not necessarily through teleport. So remove it.

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +infra_project=`realpath $1`
so what if realpath is not available?

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +  exit 1
use iteration over array instead of copy paste code.

```bash
COMMANDS="git_crypt kubectl kustomize"
for cmd in ${COMMANDS}; do
  _seek_deploy_key $path "${CLIENT}-$comp-deploy-key"
done
```

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +
declare all the VARS at the top of your file, then proceed with your business logic. Don't have vars too far from the start of your file

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +if ! [[ -f "git-crypt-key" ]]; then
hard to read this code. If you plan to say
hey generate the git-crypt-key on the very FIRST run - then make `ELSE` in the `IF` block on line 44.

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +cat << EOF  >  terraform-pod-patch.yaml
use `<<-` which allows you to PAD the code with tabs. (Don't use spaces, as <<- only removes leading tabs

sample I use:

```
_repos()
{

		#
		# export ssh keys as secrets
		# we should export only 2 private SSH keys for repositories
		# kubernetes-aws and saritasa-helm-charts
		#

		local keys="saritasa-devops-helm-charts-deploy-key.pem ${CLIENT}-kubernetes-aws-deploy-key.pem"

		pecho "provision saritasa-nest repos for argocd"

		for f in $keys
		do
			#
			# where to store the generated yaml file of the secret
			#

			local output="../repos/${f%-deploy-key.pem}.yaml"

			#
			# name of the git repository in `saritasa-nest` github org
			#

			local repo=${f%-deploy-key.pem}


			#
			# it is important to make sure you always use tab indentation when you work with <<- EOF
			# because <<- EOF removes leading tabs, but NOT the spaces. So for actual indentation you should spaces
			# but for in-code bash indentation use tabs
			#

			ssh_key=$(cat ../$f | awk '{print "    "$0}') && cat <<- EOF > $output
				apiVersion: v1
				kind: Secret
				metadata:
				  name: $repo
				  namespace: ${NAMESPACE}
				  labels:
				    argocd.argoproj.io/secret-type: repository
				stringData:
				  url: git@github.com:saritasa-nest/$repo.git
				  sshPrivateKey: |
				$ssh_key
			EOF

			pecho "generated ../repos/$output repo secret"
			kubectl apply -f $output

		done

		# this is used only as template
		# so let's remove it
		rm -rf ../repos/kubernetes-aws-repo.yaml
}

```

https://unix.stackexchange.com/questions/360800/what-does-eoc-means

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +  exit 1
See my validation commands:
https://gist.github.com/dmitry-mightydevops/bda4610b79141166955b881257db5307
let's use
- _validate_commands
- _validate_kube_context
- _validate_kube_connectivity

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +kubectl config use-context teleport.saritasa.cloud-teleport.saritasa.cloud
better use validator function

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +pod=$(kubectl apply -k . | grep pod | awk '{print $1}')
use filter by label, and then pass it into wait
```
kubectl wait --for=condition=READY --timeout=120s $(kubectl -n argo-cd get po -l app.kubernetes.io/part-of=argocd --no-headers -o="custom-columns=NAME:.metadata.name")
```

2021-12-22 01:23 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +kubectl delete -k .
unsafe. 
1. Ask the user for confirmation, use bash `confirm`
2. when you delete - delete the created resource by name you get by filter.

2021-12-22 06:40 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +cat << EOF  >  terraform-pod-patch.yaml
I don't get if, why we should PAD manifest creation with tabs? But for nested command that is a cool feature.

2021-12-22 06:44 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +cat << EOF  >  terraform-pod-patch.yaml
So the manifest is easier to read between eOf doc block

2021-12-22 06:47 UTC, MikhailKorol-saritasa commented
>has this been moved to https://github.com/saritasa-nest/saritasa-cloud-eks-cluster?

I created patch for cloud, but got some issue with kustomize:
<img width="889" alt="cloud_kustomize_issue" src="https://user-images.githubusercontent.com/88301113/147047593-0739a26c-67e9-4eb8-968e-255c3973b83a.png">
Here is PR: https://github.com/saritasa-nest/saritasa-cloud-eks-cluster/pull/2

2021-12-22 06:51 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +kubectl config use-context teleport.saritasa.cloud-teleport.saritasa.cloud
Ok, mb we can use `--dry-run`?

2021-12-22 06:53 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +infra_project=`realpath $1`
Changed to `readlink -f`

2021-12-22 06:53 UTC, dmitry-mightydevops commented
> @dmitry-saritasa
> 
> > has this been moved to https://github.com/saritasa-nest/saritasa-cloud-eks-cluster?
> 
> I created patch for cloud, but got some issue with kustomize, still working on it <img alt="cloud_kustomize_issue" width="889" src="https://user-images.githubusercontent.com/88301113/147047593-0739a26c-67e9-4eb8-968e-255c3973b83a.png"> Here is PR: [saritasa-nest/saritasa-cloud-eks-cluster#2](https://github.com/saritasa-nest/saritasa-cloud-eks-cluster/pull/2)

So I’m not sure I understand. You have issue or it’s already been transferred? Or it’s transferred and still have issue? )

2021-12-22 06:54 UTC, dmitry-mightydevops commented on terraform/terraform-pod
> +kubectl config use-context teleport.saritasa.cloud-teleport.saritasa.cloud
I don’t think config has —dry-run, I’m from iPad, but I do think dry run is apply mode only

2021-12-22 07:02 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +  exit 1
Done

2021-12-22 07:10 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +
We can't fill vars before checks cause we need to be inside target git repo. Also they are filled automatically, so no need change them.

2021-12-22 07:21 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +if ! [[ -f "git-crypt-key" ]]; then
Done.

2021-12-22 07:32 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +pod=$(kubectl apply -k . | grep pod | awk '{print $1}')
Done.

2021-12-22 07:49 UTC, MikhailKorol-saritasa commented
@dmitry-mightydevops 
>So I’m not sure I understand. You have issue or it’s already been transferred? Or it’s transferred and still have issue? )
No, it's not transferred yet, still working on it. Mb today it will be ready.

2021-12-23 02:22 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +kubectl delete -k .
1. I consider that we should always clean up, i see no reason to leave it on cluster. But we can leave files.
2. We can use internal folder for files.

2022-01-10 14:04 UTC, SergeyDeminSaritasa approved these changes

2022-01-17 11:19 UTC, MikhailKorol-saritasa commented on terraform/terraform-pod
> +kubectl config use-context teleport.saritasa.cloud-teleport.saritasa.cloud
I think it's better stay it, this script hardly bounded to cloud cluster.

2022-01-17 11:20 UTC, MikhailKorol-saritasa commented
Will merged after https://github.com/saritasa-nest/saritasa-cloud-eks-cluster/pull/2 and https://github.com/saritasa-nest/saritasa-cloud-eks-cluster/pull/1

2022-01-21 10:59 UTC, SergeyDeminSaritasa approved these changes

2022-04-25 06:58 UTC, MikhailKorol-saritasa commented
Merged as ready for work

2022-04-25 06:58 UTC, merged